spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    #local url: jdbc:mysql://localhost:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
    #local password: Hello1234!
    ##########################
    #url: jdbc:mysql://awsbd-test.cyac6dzv6rik.us-east-1.rds.amazonaws.com:3306/testDB?useSSL=false&allowPublicKeyRetrieval=true
    #username: root
    #password: Hello1234  
    #url: jdbc:mysql://mydb:3306/testDB?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://192.168.1.113:3306/testDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 8888   
  

##
  jpa:
    hibernate:
      ddl-auto: update
      dialect: MySQL8Dialect
 
server:
  port : 8081 
  
       
#  spring:
#  jackson:
#    default-property-inclusion: use_defaults/always/non-null/non-empty/non-absent/non-default
#    serialization:
#      CLOSE_CLOSEABLE: true/false
#      EAGER_SERIALIZER_FETCH: true/false
#      FAIL_ON_EMPTY_BEANS: true/false
#      FAIL_ON_SELF_REFERENCES: true/false
#      FAIL_ON_UNWRAPPED_TYPE_IDENTIFIERS: true/false
#      FLUSH_AFTER_WRITE_VALUE: true/false
#      INDENT_OUTPUT: true/false
#      ORDER_MAP_ENTRIES_BY_KEYS: true/false
#      USE_EQUALITY_FOR_OBJECT_ID: true/false
#      WRAP_EXCEPTIONS: true/false
#      WRAP_ROOT_VALUE: true/false
#      WRITE_BIGDECIMAL_AS_PLAIN: true/false
#      WRITE_CHAR_ARRAYS_AS_JSON_ARRAYS: true/false
#      WRITE_DATES_AS_TIMESTAMPS: true/false
#      WRITE_DATES_WITH_ZONE_ID: true/false
#      WRITE_DATE_KEYS_AS_TIMESTAMPS: true/false
#      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: true/false
#      WRITE_DURATIONS_AS_TIMESTAMPS: true/false
#      WRITE_EMPTY_JSON_ARRAYS: true/false
#      WRITE_ENUMS_USING_INDEX: true/false
#      WRITE_ENUMS_USING_TO_STRING: true/false
#      WRITE_ENUM_KEYS_USING_INDEX: true/false
#      WRITE_NULL_MAP_VALUES: true/false
#      WRITE_SELF_REFERENCES_AS_NULL: true/false
#      WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED: true/false
#    deserialization:
#      ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT: true/false
#      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true/false
#      ACCEPT_FLOAT_AS_INT: true/false
#      ACCEPT_SINGLE_VALUE_AS_ARRAY: true/false
#      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: true/false
#      EAGER_DESERIALIZER_FETCH: true/false
#      FAIL_ON_IGNORED_PROPERTIES: true/false
#      FAIL_ON_INVALID_SUBTYPE: true/false
#      FAIL_ON_MISSING_CREATOR_PROPERTIES: true/false
#      FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY: true/false
#      FAIL_ON_NULL_CREATOR_PROPERTIES: true/false
#      FAIL_ON_NULL_FOR_PRIMITIVES: true/false
#      FAIL_ON_NUMBERS_FOR_ENUMS: true/false
#      FAIL_ON_READING_DUP_TREE_KEY: true/false
#      FAIL_ON_TRAILING_TOKENS: true/false
#      FAIL_ON_UNKNOWN_PROPERTIES: true/false
#      FAIL_ON_UNRESOLVED_OBJECT_IDS: true/false
#      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: true/false
#      READ_ENUMS_USING_TO_STRING: true/false
#      READ_UNKNOWN_ENUM_VALUES_AS_NULL:true/false
#      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true/false
#      UNWRAP_ROOT_VALUE: true/false
#      UNWRAP_SINGLE_VALUE_ARRAYS: true/false
#      USE_BIG_DECIMAL_FOR_FLOATS: true/false
#      USE_BIG_INTEGER_FOR_INTS: true/false
#      USE_JAVA_ARRAY_FOR_JSON_ARRAY: true/false
#      USE_LONG_FOR_INTS: true/false
#      WRAP_EXCEPTIONS: true/false 